[versions]
kotlinVersion = "2.0.0"
gsonVersion = "2.11.0"

[libraries]
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gsonVersion" }

[bundles]

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlinVersion" }